### ISSUE TITLE
Add readme file

### ISSUE THREAD

**Issue by MariamKipshidze** [4n1bedoshvili/Python_lecture_2_homework#1]
რეპოზიტორიებს თან ურთავენ reamde ფაილებს სადაც წერენ მოკლე აღწერას იმისას თუ რა ხდება კოდში და როგორ ფუქციონირებს, შეგვიძლია ამ რეპოზიტორიას დავუმატოთ
რეადმე ფაილში შეგიძლია გუწერო ამოცანის პირობა და პითონის ვერსია რომელსაც იყენებ

**Comment by 4n1bedoshvili** [comment]
პირველ ლექციაზე ხომ გვითხარი და გადამავიწყდა </333 ახლავე დავამატებბ მადლობა <3
