### ISSUE TITLE
როდესაც სტრინგ ტიპის მონაცემი შემყავს ერორზე გადის ჯოდი

### ISSUE THREAD

**Issue by MariamKipshidze** [4n1bedoshvili/Python_lecture_2_homework#2]
https://github.com/4n1bedoshvili/Python_lecture_2_homework/blob/49f169bc9a108dab4d69aa99f8b1f393c3b5b4d7/Lecture_2_homework.py#L10

python vertion == Python 3.11.9

![error](https://github.com/user-attachments/assets/a5c85e3d-f702-42ad-b96d-2d3b49e8e4e3)

**Comment by 4n1bedoshvili** [comment]
უიჰ, შევასწორებ და აუცილებლად გაგებინებ რომ შევცვლი
